# Working directory
root = "."
tmp_dir = "tmp"

# Build settings
[build]
cmd = "go build -o ./tmp/main ."   # Build output
bin = "tmp/main"                   # Binary to run
full_bin = "tmp/main"              # Full path to binary
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "yaml", "yml", "json"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
kill_delay = 500
delay = 1000

# Logging
log_color = "true"
log_time = "true"

# Misc
[screen]
clear_on_rebuild = true

